CREATE DATABASE Base1;
USE Base1;

CREATE TABLE Utilisateurs(
    IdUser INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Prenom VARCHAR (100) NOT NULL,
    Nom VARCHAR (100) NOT NULL,
    Pseudo VARCHAR (100) NOT NULL,
    Email VARCHAR (100) NOT NULL UNIQUE,
    MotDePasse VARCHAR (100) NOT NULL 
);